---
servername: "test.domain.ru"
nginx_url: 
 - "test.domain.ru"
 - "test1.domain.ru"
documentroot: "/var/www/test.domain.ru"
certbot_nginx_cert_name: mycert
domain_name: test.domain.ru
ansible_python_interpreter: /usr/bin/python3
nginx_additional_urls: test.domain.ru

nginx_destination: http://test.domain.ru
